<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Cryptunnel</AssemblyName>
    <RootNamespace>Cryptunnel.App</RootNamespace>
    <Version>1.6.0</Version>
    <Company>Cryptunnel</Company>
    <ApplicationIcon>assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="assets\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cryptunnel.Core\Cryptunnel.Core.csproj" />
  </ItemGroup>

</Project>
